---

- name: Switch to local mirror
  when: apt_local_use_mirror | bool
  block:

    - name: Point ubuntu repositories to local mirror
      ansible.builtin.replace:
        path: /etc/apt/sources.list
        regexp: '^deb http(s)*://([a-z0-9\.\-_]+)\.ubuntu\.com/([a-z0-9\.\-_]+)(/)*\s+(.*)'
        replace: "deb {{ apt_local_mirror }}/ \\5"
        backup: yes
      register: __local_mirror

    - name: Disable backports
      ansible.builtin.replace:
        path: /etc/apt/sources.list
        regexp: "^deb ({{ apt_local_mirror }} {{ ansible_distribution_release }}-backports) (.*)"
        replace: "#deb \\1 \\2"
        backup: "{{ False if __local_mirror.changed else True }}"
      when: apt_local_disable_backports | bool

- name: Switch back to official mirrors
  when: not apt_local_use_mirror | bool
  block:

    - name: Replace internal mirror with public Ubuntu mirrors (non-security)
      ansible.builtin.replace:
        path: /etc/apt/sources.list
        # Match release, -updates, and -backports, but NOT -security
        regexp: '{{ apt_local_mirror }}(/)*\s+{{ ansible_distribution_release }}(?!(?:-security))(-[\w]+)?\s+(.*)'
        replace: 'http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}\2 \3'
        backup: yes

    - name: Replace internal mirror with public Ubuntu mirrors (security)
      ansible.builtin.replace:
        path: /etc/apt/sources.list
        regexp: '{{ apt_local_mirror }}(/)*\s+{{ ansible_distribution_release }}-security\s+(.*)'
        replace: 'http://security.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-security \2'
        backup: yes
